crowdfunding/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from crowdfunding import views

app_name = 'crowdfunding'
urlpatterns = [
    # ex: /crowdfunding/
    url(r'^$', views.index, name='index'),
    url(r'^business/(?P<campaign_id>[0-9]+)/$', views.business_campaign_view, name='business_campaign_view'),
    url(r'^create_campaign/$', views.CreateCampaignView.as_view(), name='create_campaign'),
    url(r'^create_donation/(?P<campaign_id>[0-9]+)/$', views.create_donation, name='create_donation'),
    #url(r'^mpesa_lipa/$', views.get_mpesa_token, name='get_mpesa_token'),
    url(r'^mpesa_checkout_response$', views.get_online_checkout_response, name='get_online_checkout_response'),
    url(r'^register_url$', views.register_url, name='register_url'),
    url(r'^confirmation_url$', views.confirmation_url, name='confirmation_url'),
    url(r'^validation_url$', views.validation_url, name='validation_url'),
    url(r'^make_payment/$', views.make_payment, name='make_payment'),
    url(r'^filter_campaign/$', views.filter_campaign_view, name='filter_campaign'),

    #crowdfunder
    url(r'^crowdfunder/$', views.crowdfunderindex, name='crowdfunderindex'),
    url(r'^crowdfunder/filter_campaign/$', views.crowdfunder_filter_campaign_view, name='crowdfunder_filter_campaign'),
    url(r'^crowdfunder/create_donation/(?P<campaign_id>[0-9]+)/$', views.crowdfunder_create_donation, name='crowdfunder_create_donation'),
    url(r'^crowdfunder/make_payment/$', views.crowdfunder_make_payment, name='crowdfunder_make_payment'),
    url(r'^crowdfunder/paypal-transaction-complete$', views.verify_paypal_payment_funder, name='verify_paypal_payment_funder'),
]

events/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from events import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(),
        name='events_home'),
    url(r'-network$', views.NetworkEventsView.as_view(),
        name='network_events'),
    url(r'^-content/(?P<pk>\d+)/$',
        views.SingleEventView.as_view(), name='event_view_content'),
    url(r'^-network/(?P<pk>\d+)/$',
        views.SingleEventView.as_view(), name='network_event_view_content'),
    url(r'^-content/filter/(?P<pk>\d+)/$',
        views.EventFilterView.as_view(), name='event_view_content_filter'),
    url(r'^-network/filter/(?P<pk>\d+)/$',
        views.NetworkEventFilterView.as_view(), name='network_event_filter'),
    url(r'^-register/(?P<event>\d+)/$',
        views.EventRegisterView.as_view(), name='event_register'),

]

venturelift_cms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from newsletter_subscription.backend import ModelBackend
from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from venturelift_media.models import Subscription
from django_registration.backends.activation.views import RegistrationView
from django.views.generic import TemplateView
from venturelift_cms import views

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^profile/', include('venturelift_profiles.urls')),
    url(r'^crowdfunding/', include('crowdfunding.urls')),
    url(r'^knowledge-center/', include('knowledge_center.urls')),
    url(r'^events', include('events.urls')),
    url(r'^registration/', RegistrationView.as_view(), name='registration_in'),
    url(r'^newsletter/', include(newsletter_subscriptions_urlpatterns(backend=ModelBackend(Subscription),))),
    url(r'^$', TemplateView.as_view(template_name="landing.html")),
    #url(r'^$', views.media_index),
    url(r'^about-us/', TemplateView.as_view(template_name="page_about_us.html")),
    url(r'^advertise/', TemplateView.as_view(template_name="page_advertise.html")),
    url(r'^careers/', TemplateView.as_view(template_name="page_careers.html")),
    url(r'^contact-us/', TemplateView.as_view(template_name="page_contact_us.html")),
    url(r'^help/', TemplateView.as_view(template_name="page_help.html")),
    url(r'^privacy-policy/',
        TemplateView.as_view(template_name="page_privary_policy.html")),
    url(r'^team/', TemplateView.as_view(template_name="page_team.html")),
    url(r'^terms-of-use/', TemplateView.as_view(template_name="page_terms_of_use.html"), name='terms-of-use'),
    url(r'^signup/', TemplateView.as_view(template_name="register.html")),
    url(r'^make_user/$', views.make_user, name='make_user'),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    #url(r'^', include(newsletter_subscriptions_urlpatterns(backend=ModelBackend(Subscription),))),
    url(r'^media/', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns

crowdfunding/forms.py
from crowdfunding.models import *
from django.forms import ModelForm
from django import forms
from django_select2.forms import Select2MultipleWidget, Select2Widget
from django_countries.widgets import CountrySelectWidget

class CreateCampaignForm(ModelForm):
    class Meta:
        model = Campaign
        exclude = ['created_at', 'total_funds_received', 'campaign_status','campaign_owner','funds_disbursement_status']
        widgets = {'duration': forms.DateInput(attrs={'id': 'datetimepicker12'})}
        labels = {
            "campaign_name": "Campaign Name",
            "company_name": "Company Name",
            "company_email": "Company Email (will be used to disburse the collected campaign funds)",
            "sector": "Campaign Sector",
            "duration": "Campaign Closing Date",
            "target_amount": "Target Amount",
            "campaign_image": "Campaign Thumbnail / Image",
            "short_description": "Campaign Title",
            "long_description": "Campaign Objective",
            "campaign_type": "Campaign Type",
            "campaign_reward_threshold": "Campaign Reward Threshold",
            "campaign_reward_details": "Campaign Reward Details",
            "minimum_donation": "Campaign Minimum Donation",
        }

    sector = forms.ModelChoiceField(queryset=CampaignSector.objects.all(), required=True,label='Campaign Sector',widget=Select2Widget)


class CreateCampaignPaymentForm(ModelForm):
    class Meta:
        model = CampaignPayment
        exclude = ['campaign', 'donator', 'payment_status','payment_order_number','paid']
        labels = {
            "payment_method": "Payment Method",
            "amount": "Amount to Donate",
        }

crowdfunding/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseRedirect

from crowdfunding.forms import *
from .models import Campaign, CampaignSector
from venturelift_profiles.models import Business,AllSystemUser
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, ListView, FormView, DetailView
from django.core.urlresolvers import resolve
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView, FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.mail import send_mail, EmailMultiAlternatives
from django.db.models import Q
from crowdfunding.tasks import *
from django.conf import settings
import requests
from requests.auth import HTTPBasicAuth
import json
from datetime import datetime
import base64
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import decimal

# Create your views here.
@login_required
def index(request):
    if request.user.is_authenticated() and not (request.user.business_creator.exists()) and not (
            request.user.supporter_creator.exists()) and not (request.user.investor_creator.exists()):
        return redirect(reverse('profile_create'))
    if not (request.user.is_authenticated()):
        return redirect(reverse('login'))

    campaign_list = Campaign.objects.filter(campaign_status='APPROVED')
    campaign_sectors = CampaignSector.objects.all()
    template = loader.get_template('crowdfunding/investor/index.html')

    if request.user.is_authenticated() and request.user.business_creator.exists():
            campaign_list = Campaign.objects.filter(campaign_owner=request.user).order_by('-created_at')
            template = loader.get_template('crowdfunding/business/index.html')

    context = {
        'campaign_list': campaign_list,
        'campaign_sectors': campaign_sectors
    }
    return HttpResponse(template.render(context, request))


def crowdfunderindex(request):
    campaign_list = Campaign.objects.filter(campaign_status='APPROVED')
    campaign_sectors = CampaignSector.objects.all()
    template = loader.get_template('crowdfunding/investor/crowdfunder_index.html')

    context = {
        'campaign_list': campaign_list,
        'campaign_sectors': campaign_sectors
    }
    return HttpResponse(template.render(context, request))


@login_required
def business_campaign_view(request, campaign_id):
    campaign_data = Campaign.objects.get(id=campaign_id)
    campaign_sectors = CampaignSector.objects.all()
    template = loader.get_template('crowdfunding/business/view_campaign.html')

    context = {
        'campaign_data': campaign_data,
        'campaign_sectors': campaign_sectors,
        'target_amount': "{0:,.2f}".format(campaign_data.target_amount),
        'minimum_donation': "{0:,.2f}".format(campaign_data.minimum_donation),
        'total_funds_received': "{0:,.2f}".format(campaign_data.total_funds_received),
    }
    return HttpResponse(template.render(context, request))


@login_required
def filter_campaign_view(request):
    if request.user.is_authenticated() and not (request.user.business_creator.exists()) and not (
            request.user.supporter_creator.exists()) and not (request.user.investor_creator.exists()):
        return redirect(reverse('profile_create'))
    if not (request.user.is_authenticated()):
        return redirect(reverse('login'))

    template = loader.get_template('crowdfunding/investor/index.html')
    campaign_data = Campaign.objects.filter(campaign_name__contains=request.POST['campaign_name'],campaign_status='APPROVED')

    if request.user.is_authenticated() and request.user.business_creator.exists():
        template = loader.get_template('crowdfunding/business/index.html')
        campaign_data = Campaign.objects.filter(campaign_name__contains=request.POST['campaign_name'],campaign_owner=request.user)
    if empty(request.POST['sector']):
        sector_data = CampaignSector.objects.filter(id=request.POST['sector'])
        if request.user.is_authenticated() and request.user.business_creator.exists():
            campaign_data = Campaign.objects.filter(Q(sector=sector_data) | Q(campaign_name__contains=request.POST['campaign_name'])).filter(campaign_owner=request.user)
        else:
            campaign_data = Campaign.objects.filter(Q(sector=sector_data) | Q(campaign_name__contains=request.POST['campaign_name'])).filter(campaign_status='APPROVED')
    campaign_sectors = CampaignSector.objects.all()

    context = {
        'campaign_list': campaign_data,
        'campaign_sectors': campaign_sectors
    }
    return HttpResponse(template.render(context, request))


def crowdfunder_filter_campaign_view(request):
    template = loader.get_template('crowdfunding/investor/crowdfunder_index.html')
    campaign_data = Campaign.objects.filter(campaign_name__contains=request.POST['campaign_name'],campaign_status='APPROVED')

    if empty(request.POST['sector']):
        sector_data = CampaignSector.objects.filter(id=request.POST['sector'])
        campaign_data = Campaign.objects.filter(Q(sector=sector_data) | Q(campaign_name__contains=request.POST['campaign_name'])).filter(campaign_status='APPROVED')
    campaign_sectors = CampaignSector.objects.all()

    context = {
        'campaign_list': campaign_data,
        'campaign_sectors': campaign_sectors
    }
    return HttpResponse(template.render(context, request))

def empty(value):
    try:
        value = int(value)
    except ValueError:
        pass
    return bool(value)

class CreateCampaignView(LoginRequiredMixin, CreateView):
    template_name = 'crowdfunding/business/create_campaign.html'
    form_class = CreateCampaignForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_at = timezone.now()
        self.object.total_funds_received = 0
        self.object.campaign_status = 'OPENED'
        self.object.funds_disbursement_status = 'PENDING'
        self.object.campaign_owner = self.request.user
        self.object.approval_status = "PENDING"
        self.object.approved = False
        self.object.rejected = False
        self.object.save()

        #campaign_path = reverse('admin:campaign', args=(self.object.id,))

        subject, from_email, to = 'Campaign Approval Request', settings.EMAIL_HOST_USER, settings.ADMIN_EMAIL
        send_approval_request_email_task.delay(self.object.campaign_name, self.object.id, subject, from_email, to)

        return redirect(reverse('crowdfunding:index'))

    def form_invalid(self, form):
        errors = form.errors
        raise Exception(errors)


@login_required
def create_donation(request, campaign_id):
    campaign_data = Campaign.objects.get(id=campaign_id)
    template = loader.get_template('crowdfunding/investor/create_payment.html')

    context = {
        'campaign_data': campaign_data,
        'target_amount': "{0:,.2f}".format(campaign_data.target_amount),
        'minimum_donation': "{0:,.2f}".format(campaign_data.minimum_donation),
        'total_funds_received': "{0:,.2f}".format(campaign_data.total_funds_received),
    }
    return HttpResponse(template.render(context, request))


def crowdfunder_create_donation(request, campaign_id):
    campaign_data = Campaign.objects.get(id=campaign_id)
    template = loader.get_template('crowdfunding/investor/crowdfunder_create_payment.html')

    context = {
        'campaign_data': campaign_data,
        'target_amount': "{0:,.2f}".format(campaign_data.target_amount),
        'minimum_donation': "{0:,.2f}".format(campaign_data.minimum_donation),
        'total_funds_received': "{0:,.2f}".format(campaign_data.total_funds_received),
    }
    return HttpResponse(template.render(context, request))

@csrf_exempt
def get_online_checkout_response(request):
    stkResponse = MpesaSTKResponse(name='STK Response',created_at=timezone.now(),response_json=request.body)
    stkResponse.save()
    data = json.loads(request.body)
    dataResponse = data['Body']['stkCallback']
    responseCode = dataResponse['ResultCode']
    if responseCode == 0:
        referenceCode = ''
        amount = ''
        phone = ''
        shortCode = settings.SHORTCODE
        checkoutId = dataResponse['CheckoutRequestID']
        callbackMetaData = dataResponse['CallbackMetadata']['Item']
        for item in callbackMetaData:
            if item['Name'] == "Amount":
                amount = str(item['Value'])
            if item['Name'] == "MpesaReceiptNumber":
                referenceCode = item['Value']
            if item['Name'] == "PhoneNumber":
                phone = item['Value']
        checkCheckout = MpesaSTKPush.objects.filter(checkoutID=checkoutId).first()
        if checkCheckout:
            checkout = MpesaSTKPush.objects.get(checkoutID=checkoutId)
            send_mpesa_c2b_notification_url_task.delay(checkout.name, referenceCode, amount, phone, shortCode)

    response = '{"success":"true","message":"Received"}'
    return HttpResponse(response)


@csrf_exempt
def confirmation_url(request):
    data = json.loads(request.body)
    accountName = data['BillRefNumber']
    referenceCode = data['TransID']
    amount = data['TransAmount']
    phone = data['MSISDN']
    shortCode = data['BusinessShortCode']
    #send_mpesa_c2b_notification_url_task.delay(accountName,referenceCode,amount,phone,shortCode)
    response = '{"success":"true","message":"Received"}'
    return HttpResponse(response)


@csrf_exempt
def validation_url(request):
    response = '{"success":"true","message":"Verified"}'
    return HttpResponse(response)


def register_url(request):
    send_mpesa_c2b_register_url_task.delay()

crowdfunding/templates/crowdfunding/base5.html
{% load cms_tags menu_tags sekizai_tags staticfiles %}
<!doctype html>
<html>

{% include "global-header.html" %}

<body class="crowd_base5 logged_in profile_templates">
    
    {% cms_toolbar %}

    <!-- Fixed navbar -->
    <nav id="navbar_out" class="navbar navbar-default2 navbar-fixed-top">
      <div class="top_container container">

        <div class="nav_nav_first navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <img src="{% static 'img/logo2.png' %}" alt="VentureLift Africa Media Centre">
          </a>
        </div>
        <div class="vl_top_top navbar-right collapse navbar-collapse navbar-responsive-collapse">
          <ul class="in_line">
            <li class="active"><a href="/">Home</a></li>
            <li>
              <div class="dropdown">
                <button class="dropbtn">Business</button>
                <div class="dropdown-content">
                    <a href="{% url 'registration_in' %}">Startup</a>
                    <a href="{% url 'registration_in' %}">SMEs</a>
                </div>
              </div>
            </li>
            <!--<li><a href="{% url 'registration_in' %}">Funder</a></li>-->
            <li>
              <div class="dropdown">
                <button class="dropbtn">Funder</button>
                <div class="dropdown-content">
                    <a href="{% url 'registration_in' %}">Investor</a>
                    <a href="{% url 'crowdfunding:crowdfunderindex' %}" target="_blank">Crowdfunder</a>
                    <a href="{% url 'registration_in' %}">Lender</a>
                </div>
              </div>
            </li>
            <li>
              <div class="dropdown">
                <button class="dropbtn">Partner</button>
                <div class="dropdown-content">
                    <a href="{% url 'registration_in' %}">Trade</a>
                    <a href="{% url 'registration_in' %}">Supply Chain</a>
                    <a href="{% url 'registration_in' %}">Technology</a>
                    <a href="{% url 'registration_in' %}">Talent</a>
                    <a href="{% url 'registration_in' %}">Professional Services</a>
                </div>
              </div>
            </li>
            <li><a href="{%url 'knowledge_center_home' %}">Knowledge Center</a></li>
            {% if user.is_authenticated %}
            <li><a href="{%url 'events_home' %}">Events</a></li>
            <li><a href="/en/media">VLA Media</a></li>
            <li class="user_nav_item pull_right">
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="true">
                <figure class="user_icon_nav">
                  {% if context.supporter %}
                    {% if context.supporter.thumbnail_image %}
                      <img src="{{ context.supporter.thumbnail_image.url }}">
                    {% else %}
                      {% if context.supporter.gender == 'Male' or context.supporter.gender == 'Other' %}
                      <img src="{% static 'img/blue-user-icon.svg' %}">
                      {% else %}
                      <img src="{% static 'img/no-img.jpg' %}">
                      {% endif %}
                    {% endif %}
                  {% elif context.investor %}
                    {% if context.investor.thumbnail_image %}
                      <img src="{{ context.investor.thumbnail_image.url }}">
                    {% else %}
                      {% if context.investor.gender == 'Male' or context.investor.gender == 'Other' %}
                        <img src="{% static 'img/blue-user-icon.svg' %}">
                        {% else %}
                        <img src="{% static 'img/no-img.jpg' %}">
                      {% endif %}
                    {% endif %}
                  {% elif context.business %}
                    {% if context.business.thumbnail_image %}
                    <img src="{{ context.business.thumbnail_image.url }}">
                    {% else %}
                    <img src="{% static 'img/no-img.jpg' %}">
                    {% endif %}
                  {% endif %}
                </figure>
                </button>
                <ul class="user_nav_item_drop dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
                  <li><a href="{% url 'profile_summary' %}">My Profile</a></li>
                  <div class="divider"></div>
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </div>
            </li>
            <!--
            <li class="pull_right">
              <a href="#nogo">
                <ion-icon name="notifications-outline"></ion-icon>
              </a>
            </li>
            -->
            {% else %}
            <li><a href="/en/media">VLA Media</a></li>
            <li>
              <a href="{% url 'login' %}">Sign In</a>
            </li>
            <li>
              <a class="btn btn-md btn-primary" href="{% url 'registration_in' %}">Join VentureLift Africa</a>
            </li>
            {% endif %}
          </ul>
        </div>
        
      </div>
    </nav>


    <!-- Fixed navbar 
    <nav id="navbar_out" class="navbar navbar-default2 navbar-fixed-top">
      <div class="top_container container">
        <div class="nav_nav_first navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarX" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{% url 'crowdfunding:crowdfunderindex' %}">
            <img src="{% static 'img/logo2.png' %}" alt="VentureLift Africa">
          </a>
          <div class="vl_top_top navbar-right">
            <ul class="vl_top_nav in_line">
              <li>
                <a href="{% url 'crowdfunding:crowdfunderindex' %}">
                  Crowdfunder
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    -->

        <div class="content_container">

            <div class="full_A with-side-filter">
                <div class="columns_A flex row clearfix">
                    <div class="col_A_out col_A_out_2 col-md-10 clearfix">
                        {% block content_1 %}{% endblock %}
                    </div>
                    <div class="col_A_out col_A_out_3 col-md-2 clearfix">
                        <div class="col_A_in col_A_in_co_filter">
                            {% block content_2 %}{% endblock %}
                            <div class="sidebar_actions">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

         {# include "global-footer.html" #}

      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
      {{ form.media.js }}
      <script>
          window.jQuery || document.write('<script src="js/vendor/jquery.min.js"><\/script>')
      </script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="https://unpkg.com/ionicons@4.4.8/dist/ionicons.js"></script>
      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137967572-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-137967572-1');
      </script>        

    <!-- Hotjar Tracking Code for http://vlatest.otbafrica.com -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:1462645,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>


</body>

</html>