crowdfunding/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from crowdfunding import views

app_name = 'crowdfunding'
urlpatterns = [
    # ex: /crowdfunding/
    url(r'^$', views.index, name='index'),
    url(r'^business/(?P<campaign_id>[0-9]+)/$', views.business_campaign_view, name='business_campaign_view'),
    url(r'^create_campaign/$', views.CreateCampaignView.as_view(), name='create_campaign'),
    url(r'^create_donation/(?P<campaign_id>[0-9]+)/$', views.create_donation, name='create_donation'),
    #url(r'^mpesa_lipa/$', views.get_mpesa_token, name='get_mpesa_token'),
    url(r'^mpesa_checkout_response$', views.get_online_checkout_response, name='get_online_checkout_response'),
    url(r'^register_url$', views.register_url, name='register_url'),
    url(r'^confirmation_url$', views.confirmation_url, name='confirmation_url'),
    url(r'^validation_url$', views.validation_url, name='validation_url'),
    url(r'^make_payment/$', views.make_payment, name='make_payment'),
    url(r'^filter_campaign/$', views.filter_campaign_view, name='filter_campaign'),

    #crowdfunder
    url(r'^crowdfunder/$', views.crowdfunderindex, name='crowdfunderindex'),
    url(r'^crowdfunder/filter_campaign/$', views.crowdfunder_filter_campaign_view, name='crowdfunder_filter_campaign'),
    url(r'^crowdfunder/create_donation/(?P<campaign_id>[0-9]+)/$', views.crowdfunder_create_donation, name='crowdfunder_create_donation'),
    url(r'^crowdfunder/make_payment/$', views.crowdfunder_make_payment, name='crowdfunder_make_payment'),
    url(r'^crowdfunder/paypal-transaction-complete$', views.verify_paypal_payment_funder, name='verify_paypal_payment_funder'),
]

events/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from events import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(),
        name='events_home'),
    url(r'-network$', views.NetworkEventsView.as_view(),
        name='network_events'),
    url(r'^-content/(?P<pk>\d+)/$',
        views.SingleEventView.as_view(), name='event_view_content'),
    url(r'^-network/(?P<pk>\d+)/$',
        views.SingleEventView.as_view(), name='network_event_view_content'),
    url(r'^-content/filter/(?P<pk>\d+)/$',
        views.EventFilterView.as_view(), name='event_view_content_filter'),
    url(r'^-network/filter/(?P<pk>\d+)/$',
        views.NetworkEventFilterView.as_view(), name='network_event_filter'),
    url(r'^-register/(?P<event>\d+)/$',
        views.EventRegisterView.as_view(), name='event_register'),

]

venturelift_cms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from newsletter_subscription.backend import ModelBackend
from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from venturelift_media.models import Subscription
from django_registration.backends.activation.views import RegistrationView
from django.views.generic import TemplateView
from venturelift_cms import views

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^profile/', include('venturelift_profiles.urls')),
    url(r'^crowdfunding/', include('crowdfunding.urls')),
    url(r'^knowledge-center/', include('knowledge_center.urls')),
    url(r'^events', include('events.urls')),
    url(r'^registration/', RegistrationView.as_view(), name='registration_in'),
    url(r'^newsletter/', include(newsletter_subscriptions_urlpatterns(backend=ModelBackend(Subscription),))),
    url(r'^$', TemplateView.as_view(template_name="landing.html")),
    #url(r'^$', views.media_index),
    url(r'^about-us/', TemplateView.as_view(template_name="page_about_us.html")),
    url(r'^advertise/', TemplateView.as_view(template_name="page_advertise.html")),
    url(r'^careers/', TemplateView.as_view(template_name="page_careers.html")),
    url(r'^contact-us/', TemplateView.as_view(template_name="page_contact_us.html")),
    url(r'^help/', TemplateView.as_view(template_name="page_help.html")),
    url(r'^privacy-policy/',
        TemplateView.as_view(template_name="page_privary_policy.html")),
    url(r'^team/', TemplateView.as_view(template_name="page_team.html")),
    url(r'^terms-of-use/', TemplateView.as_view(template_name="page_terms_of_use.html"), name='terms-of-use'),
    url(r'^signup/', TemplateView.as_view(template_name="register.html")),
    url(r'^make_user/$', views.make_user, name='make_user'),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    #url(r'^', include(newsletter_subscriptions_urlpatterns(backend=ModelBackend(Subscription),))),
    url(r'^media/', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns

venturelift_profiles/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from venturelift_profiles import views
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^accounts/activate/complete/$',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'),
    # override the django_registration activation view
    url(r'^accounts/activate/(?P<activation_key>[-:\w]+)/$',
        views.ProfileActivationView.as_view(),
        name='django_registration_activate'),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile/$', views.SummaryView.as_view(), name='profile_summary'),
    url(r'^supporter/list/$', views.SupporterView.as_view(), name='supporter_list'),
    url(r'^supporter/list/filter/(?P<supporter_type>[\w ]+)/$',
        views.SupporterFilterView.as_view(), name='supporter_filter'),
    url(r'^business/list/$', views.BusinessView.as_view(), name='business_list'),
    url(r'^business/list/startup/$',
        views.BusinessStartupView.as_view(), name='business_startup'),
    url(r'^business/list/smes/$',
        views.BusinessSMEView.as_view(), name='business_smes'),
    url(r'^investor/list/$', views.InvestorView.as_view(), name='investor_list'),
    url(r'^investor/list/filter/(?P<investor_type>[\w ]+)/$',
        views.InvestorFilterView.as_view(), name='investor_filter'),
    url(r'^supporter/follow/(?P<pk>\d+)/$',
        views.SupporterView.as_view(), name='supporter_follow'),
    url(r'^supporter/unfollow/(?P<pk>\d+)/$',
        views.SupporterView.as_view(), name='supporter_unfollow'),

    url(r'^business/follow/(?P<pk>\d+)/$',
        views.BusinessView.as_view(), name='business_follow'),

    url(r'^business/unfollow/(?P<pk>\d+)/$',
        views.BusinessView.as_view(), name='business_unfollow'),

    url(r'^investor/follow/(?P<pk>\d+)/$',
        views.InvestorView.as_view(), name='investor_follow'),

    url(r'^investor/unfollow/(?P<pk>\d+)/$',
        views.InvestorView.as_view(), name='investor_unfollow'),

    url(r'^business/profile/(?P<pk>\d+)/$',
        views.BusinessProfileView.as_view(), name='business_profile'),

    url(r'^supporter/profile/(?P<pk>\d+)/$',
        views.SupporterProfileView.as_view(), name='supporter_profile'),

    url(r'^investor/profile/(?P<pk>\d+)/$',
        views.InvestorProfileView.as_view(), name='investor_profile'),

    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^post-like/(?P<pk>\d+)/$', views.SummaryView.as_view(), name='like_post'),
    url(r'^post-dislike/(?P<pk>\d+)/$',
        views.SummaryView.as_view(), name='dislike_post'),
    url(r'^create-business/step-1/$', views.CreateBusinessView.as_view(),
        name='create_business_step1'),
    url(r'^create-business/step-1/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step1'),
    url(r'^create-business/step-2/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step2'),
    url(r'^create-business/step-3/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step3'),
    url(r'^create-business/step-4/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step4'),
    url(r'^create-business/step-5/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step5'),
    url(r'^create-business/step-6/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step6'),
    url(r'^create-business/step-7/(?P<pk>\d+)/$',
        views.UpdateBusinessView.as_view(), name='update_business_step7'),
    url(r'^profile-create/$', views.ProfileCreateView.as_view(), name='profile_create'),
    url(r'^supporter-create/$', views.CreateSupporterView.as_view(),
        name='supporter_create'),
    url(r'^supporter-create/step-1/(?P<pk>\d+)/$', views.SupporterUpdateProfileView.as_view(),
        name='update_supporter_step1'),
    url(r'^supporter-create/step-2/(?P<pk>\d+)/$', views.SupporterUpdateProfileView.as_view(),
        name='update_supporter_step2'),
    url(r'^new-document-upload/$', views.CreateBlogPostView.as_view(), name='new_blog_post'),
    url(r'^investor-create/$', views.CreateInvestorView.as_view(),
        name='investor_create'),
    url(r'^investor-create/step-1/(?P<pk>\d+)/$',
        views.InvestorUpdateProfileView.as_view(), name='update_investor_step1'),
    url(r'^investor-create/step-2/(?P<pk>\d+)/$',
        views.InvestorUpdateProfileView.as_view(), name='update_investor_step2'),
    # url(r'^account_activation/$',
    #    views.VerificationAccountWaiting.as_view(), name='account_verification_waiting'),
]

venturelift_profiles/templates/profile/base.html
{% load cms_tags menu_tags sekizai_tags staticfiles %}
<!doctype html>
<html>

<head>
    <title>{% block title %}VentureLift Africa - Portal{% endblock title %}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#283891">

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/menu-dropdown.css' %}" rel="stylesheet">
    {{ form.media.css }}
    {% render_block "css" %}
</head>


<body class="profile-base logged_in profile_templates">
    {% cms_toolbar %}
        <!-- Fixed navbar -->
    <nav id="navbar_out" class="navbar navbar-default2 navbar-fixed-top">
      <div class="top_container container">
        <div class="nav_nav_first navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{% url 'profile_summary' %}">
            <img src="{% static 'img/logo2.png' %}" alt="VentureLift Africa">
          </a>
        </div>
        
        <div class="vl_top_top navbar-right collapse navbar-collapse navbar-responsive-collapse">
          <ul class="vl_top_nav in_line">
            <li>
              <a href="/">
                Home
              </a>
            </li>
          <li>
            <div class="dropdown">
              <button class="dropbtn">Business</button>
              <div class="dropdown-content">
                  <a href="{% url 'business_startup' %}">Startup</a>
                  <a href="{% url 'business_smes' %}">SMEs</a>
              </div>
            </div>
          </li>
        <li>
          <div class="dropdown">
            <button class="dropbtn">Funder</button>
            <div class="dropdown-content">
               <a href="{% url 'investor_filter' 'Investor' %}">Investor</a>
               <a href="{% url 'crowdfunding:index' %}">Crowdfunder</a>
               <a href="{% url 'investor_filter' 'Lender' %}">Lender</a>
               <a href="{% url 'investor_filter' 'Grantor' %}">Grantor</a>
            </div>
          </div>
        </li>
          <li>
            <div class="dropdown">
              <button class="dropbtn">Partner</button>
              <div class="dropdown-content">
                  <a href="{% url 'supporter_filter' 'Trade' %}">Trade</a>
                  <a href="{% url 'supporter_filter' 'Supply Chain' %}">Supply Chain</a>
                  <a href="{% url 'supporter_filter' 'Technology' %}">Technology</a>
                  <a href="{% url 'supporter_filter' 'Talent' %}">Talent</a>
                  <a href="{% url 'supporter_filter' 'Professional Services' %}">Professional Services</a>
              </div>
            </div>
          </li>
            <li>
              <a href="{%url 'knowledge_center_home' %}">
                Knowledge Center
              </a>
            </li>
            <li>
              <a href="{%url 'events_home' %}">
                Events
              </a>
            </li>
            <li>
              <a href="/en/media">
              VLA Media
              </a>
            </li>
            <li class="user_nav_item pull_right">
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="true">
                <figure class="user_icon_nav">
                  {% if context.supporter %}
                    {% if context.supporter.thumbnail_image %}
                      <img src="{{ context.supporter.thumbnail_image.url }}">
                    {% else %}
                      {% if context.supporter.gender == 'Male' or context.supporter.gender == 'Other' %}
                      <img src="{% static 'img/blue-user-icon.svg' %}">
                      {% else %}
                      <img src="{% static 'img/no-img.jpg' %}">
                      {% endif %}
                    {% endif %}
                  {% elif context.investor %}
                    {% if context.investor.thumbnail_image %}
                      <img src="{{ context.investor.thumbnail_image.url }}">
                    {% else %}
                      {% if context.investor.gender == 'Male' or context.investor.gender == 'Other' %}
                        <img src="{% static 'img/blue-user-icon.svg' %}">
                        {% else %}
                        <img src="{% static 'img/no-img.jpg' %}">
                      {% endif %}
                    {% endif %}
                  {% elif context.business %}
                    {% if context.business.thumbnail_image %}
                    <img src="{{ context.business.thumbnail_image.url }}">
                    {% else %}
                    <img src="{% static 'img/no-img.jpg' %}">
                    {% endif %}
                  {% endif %}
                </figure>
                </button>
                <ul class="user_nav_item_drop dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
                  <li><a href="{% url 'profile_summary' %}">My Profile</a></li>
                  <div class="divider"></div>
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </div>
            </li>
            <!--
            <li class="pull_right"><a href="#nogo">
                <ion-icon name="notifications-outline"></ion-icon>
              </a>
            </li>
            -->
          </ul>
        </div>
        
      </div>
    </nav>
    <div class="content_container">

        <div class="full_A with-side-filter">
            <div class="columns_A flex row clearfix">
                <div class="col_A_out col_A_out_2 col-md-12 clearfix">
                    {% block content_1 %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

    <div class="full_width footer">
        {# static_placeholder 'footer' #}
    </div>

    <div class="full_width primary_footer">
        <div class="full_width footer foot2">
            <div class="container clearfix">
                <ul class="in_style_A_list_A in_style_B1">
                    <li><a href="/about-us">About us</a></li>
                    <li><a href="/team">Leadership</a></li>
                    <li><a href="/careers">Careers</a></li>
                    <li><a href="/help">FAQ</a></li>
                    <li><a href="/advertise">Advertise</a></li>
                    <li><a href="/terms-of-use">Terms of Use</a></li>
                    <li><a href="/contact-us">Contact us</a></li>
                </ul>      
                <ul class="in_style_A_list_A in_style_B3">
                    <li>
                      <ul class="social_icons social_bottom">
                        <li><a class="li" href="https://ke.linkedin.com/company/venturelift-africa"><ion-icon name="logo-linkedin" role="img" class="hydrated" aria-label="logo linkedin"></ion-icon></a></li>
                        <li><a class="tw" href="https://twitter.com/vliftafrica"><ion-icon name="logo-twitter" role="img" class="hydrated" aria-label="logo twitter"></ion-icon></a></li>
                        <li><a class="fb" href="https://facebook.com/vlafrica"><ion-icon name="logo-facebook" role="img" class="hydrated" aria-label="logo facebook"></ion-icon></a></li>
                        <li><a class="ig" href="https://www.instagram.com/vliftafrica/"><ion-icon name="logo-instagram" role="img" class="hydrated" aria-label="logo instagram"></ion-icon></a></li>
                      </ul>
                    </li>
                </ul>
                <ul class="in_style_A_list_A in_style_B2">
                    <li class="copright"><a href="{% url 'terms-of-use' %}">&copy; 2020. All Rights Reserved | Terms of Use</a></li>
                </ul>                              
            </div>
        </div>        
        {# static_placeholder 'footer' #}
    </div>

    <div id="sampleProfile" style="">
      <p>This is a sample profile</p>
    </div>
    
    <style>
      .in_style_A_list_A a{
        text-decoration: none;
        color: #ffffff;
      }
    </style>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    {{ form.media.js }}
    <script>
        window.jQuery || document.write('<script src="js/vendor/jquery.min.js"><\/script>')
    </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
     {% block javascript %}{% endblock %}
    <script src="https://unpkg.com/ionicons@4.4.8/dist/ionicons.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137967572-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-137967572-1');
    </script>

    <!-- Hotjar Tracking Code for http://vlatest.otbafrica.com -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:1462645,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

</body>

</html>

venturelift_profiles/templates/profile/create_post.html
{% extends 'portal_base.html' %}
{% load crispy_forms_tags %}

{% block content_1 %}

<div class="col_A_in col_A_in_2">
    <form method='post'>
        {% csrf_token %}
        <div class="form-group col-md-6 mb-0">
            {{ form|crispy }}
            <button type='submit' class='btn btn-primary'>Create Post</button>
        </div>
    </form>
</div>


{% endblock %}
{% block content_2 %}
<div class="company_filter">
    <h4>Sidebar</h4>
</div>
{% endblock %}

venturelift_profiles/templates/profile/profile.html
{% extends 'profile/base2.html' %}
{% block content %}

<div class="full_A full_width">
	<div class="columns_A flex row clearfix">
		<div class="col-md-4 clearfix">
			<div class="col_A_in col_A_in_1">
				<h3>User profile</h3>
				<p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
			</div>
		</div>
		<div class="col-md-8 clearfix">
			<div class="col_A_in col_A_in_2">
				<h4>Updates</h4>
			</div>
		</div>
	</div>
</div>

{% endblock %}

venturelift_profiles/templates/profile/profile_create.html
{% extends 'profile/base3.html' %}
{% load crispy_forms_tags %}

{% block content %}


<link rel="stylesheet" type="text/css"
  href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<style type="text/css">
  .section {
    display: flex;
    flex-flow: row wrap;
    margin: 30px 0px 10px;
  }

  .section>div {
    flex: 1;
    padding: 0.5rem;
    margin: 5px;
  }

  .section input[type="radio"] {
    display: none;

    &:not(:disabled)~label {
      cursor: pointer;
    }

    &:disabled~label {
      color: hsla(150, 5%, 75%, 1);
      border-color: hsla(150, 5%, 75%, 1);
      box-shadow: none;
      cursor: not-allowed;
    }
  }

  .section label {
    height: 100%;
    display: block;
    background: white;
    border: 1px solid hsla(150, 75%, 50%, 0.15);
    border-radius: 20px;
    padding: 1rem;
    margin-bottom: 1rem;
    text-align: center;
    box-shadow: 0px 3px 10px -2px hsla(150, 5%, 65%, 0.5);
    position: relative;
    color: #20df80;
  }

  .section input[type="radio"]:checked+label {
    background: hsla(150, 75%, 50%, 1);
    color: hsla(215, 0%, 100%, 1);
    box-shadow: 0px 0px 20px hsla(150, 100%, 50%, 0.75);

    &::after {
      color: hsla(215, 5%, 25%, 1);
      font-family: FontAwesome;
      border: 2px solid hsla(150, 75%, 45%, 1);
      content: "\f00c";
      font-size: 24px;
      position: absolute;
      top: -25px;
      left: 50%;
      transform: translateX(-50%);
      height: 50px;
      width: 50px;
      line-height: 50px;
      text-align: center;
      border-radius: 50%;
      background: white;
      box-shadow: 0px 2px 5px -2px hsla(0, 0%, 0%, 0.25);
    }
  }

  .section input[type="radio"]#control_05:checked+label {
    background: red;
    border-color: red;
  }

  @media only screen and (max-width: 700px) {
    .section {
      flex-direction: column;
    }
  }

  section.section h2 {
    font-weight: 100;
    font-size: 1.7em;
    margin-top: 26px;
  }
</style>



<div class='container'>
  <div class="onboarding_A">


    <div class="row clearfix">
      <form action="{% url 'profile_create' %}" method="POST">
        {% csrf_token %}
        <div class="col-md-6 col-md-offset-3 clearfix">
          <div class="text-center">
            <h3>Great! Let's start by setting up your profile</h3>
            <br>
          </div>

          <section class="section">
            <div>
              <input type="radio" id="control_01" name="profile_choice" value="Business" checked>
              <label for="control_01">
                <div class="select_icon">
                  <ion-icon name="briefcase"></ion-icon>
                </div>
                <h2>I am a business</h2>
              </label>
            </div>
            <div>
              <input type="radio" id="control_02" name="profile_choice" value="Investor">
              <label for="control_02">
                <div class="select_icon">
                  <ion-icon name="sunny"></ion-icon>
                </div>
                <h2>I am a funder</h2>
              </label>
            </div>
            <div>
              <input type="radio" id="control_03" name="profile_choice" value="Supporter">
              <label for="control_03">
                <div class="select_icon">
                  <ion-icon name="people"></ion-icon>
                </div>
                <h2>I am a partner</h2>
              </label>
            </div>
          </section>

          <figure class="btn_cover">
            <button class="btn btn-B">Next &rarr;</button>
          </figure>
        </div>
      </form>
    </div>













  </div>
</div>

{% endblock %}

venturelift_profiles/templates/profile/supporters.html
{% extends 'profile/base4.html' %}
{% load cms_tags staticfiles %}
{% load crispy_forms_tags %}
{% block content_1 %}


<div class="col_A_in col_A_in_2">
    <div class="topbar_2">
        <div class="row clearfix">
            <div class="col-md-6 clearfix">
                <p class="p_title">Partners</p>
            </div>
            <div class="col-md-6 clearfix">
                <div class="company_filter pull-right">
                    <form method='post' class='' action="">
                        {% csrf_token %}
                        <input class='form-control' name='supporter-name' placeholder='Search a Partner' />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class='col-md-12 clearfix'>
            <div class="row clearfix">
                {% for obj in object_list %}
                <div class="col-md-2 box_box">
                    <div class="box_box_in">
                        <figure class="box_avi">
                            <!-- Square, 350 X 350 PX -->
                            {% if obj.thumbnail_image %}
                            <img src="{{ obj.thumbnail_image.url }}">
                            {% else %}
                            <img src="{% static 'img/blue-user-icon.svg' %}">
                            {% endif %}
                        </figure>
                        <figure class="box_details">
                            <p class="box_title"><a href="{% url 'supporter_profile' obj.pk %}">{{obj.fullname}}</a></p>
                            <div class="box_social">
                                {% if obj in following %}
                                <a href="{% url 'supporter_unfollow' obj.id %}"><button
                                        class="btn-actioned btn btn-sm btn-default">Following</button></a>
                                {% else %}
                                <a href="{% url 'supporter_follow' obj.id %}"><button
                                        class=" btn btn-sm btn-default">Follow</button></a>
                                {% endif %}
                            </div>
                        </figure>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content_2 %}
<div class="company_filter">
    <h4>Filter Partners</h4>
    <ul class="search_A search_A2">
        <form method='post'>
            <li>
                {% csrf_token %}
                {{form|crispy }}
            </li>
            <li>
                <button class='btn btn-success'>Filter</button>
            </li>
        </form>
    </ul>
</div>
{% endblock %}